# -*- coding: utf-8 -*-
"""4.1.2. Melnbalts, pikseļi, proporcionāli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMYJ6YsXBrMP3i4Au1_dn27LMZ6sZ32n
"""

!pip install music21;

#tiek ieimportētas nepieciešamās bibliotēkas
from music21 import instrument, note, stream
from google.colab import files
import matplotlib.pyplot as plt
import numpy as np

#fja, kas nosaka nots augstumu (do mažorā), ja tam padod krāsas vērtību
def note_pitch (pixel):
  dens = pixel/255
  #100/7=14.285...~14.3% notij
  if dens < 0.143 : return 0 #C
  elif 0.143 <= dens < 0.286 : return 2 #D
  elif 0.286 <= dens < 0.429 : return 4 #E
  elif 0.429 <= dens < 0.572 : return 5 #F
  elif 0.572 <= dens < 0.715 : return 7 #G
  elif 0.715 <= dens < 0.858 : return 9 #A
  else: return 11 #B

#funkcija nošu un MIDI faila veidošana
def create_music (arr, fn, download=True, printMIDI=False):
  output_notes = []
  offset = 0
  
  #tiek veidoti nošu objekti katrai masīva vērtībai, nots augstumu nosakot ar fjas note_pitch palīdzību
  #parametrs quarterLenght apzīmē nots garumu ceturtdaļās
  #offset ir nots atskaņošanas laiks attiecībā pret sākumu
  for px in arr:
    note_p = note_pitch(px)
    new_note = note.Note(note_p, quarterLength=0.5)
    new_note.offset = offset
    new_note.octave = 4
    new_note.storedInstrument = instrument.Piano()
    output_notes.append(new_note)
    
    #palielina offset katrā iterācijā, lai notis nepārklājas
    offset += 0.5
      
  #ģenerēto nošu informācija tiek ierakstīta failā
  midi_stream = stream.Stream(output_notes)
  midi_stream.write('midi', fp='{name}_412.mid'.format(name=fn.split('.')[0]))

  #ģenerēto nošu izprintēšana
  if printMIDI == 1:
    for element in midi_stream:
      print(element.nameWithOctave, element.offset)

  #ģenerētā MIDI faila lejuplāde
  if download == 1:
    files.download('{name}_412.mid'.format(name=fn.split('.')[0]))
  return

#attēla augšupielāde
uploaded = files.upload()

#tiek nolasīts faila nosaukums un pats attēls
filename = list(uploaded.keys())[0]
uploaded_picture=plt.imread(filename)

#attēlam no 3 krāsu dimensijām vispirms tiek izvilkta viena, tad tā tiek saspiesta 1D masīvā
uploaded_picture_bw=np.array(uploaded_picture[:, :, 0]).reshape(uploaded_picture.shape[0]*uploaded_picture.shape[1])

#iegūtais masīvs tiek padots mūzikas ģenerēšanas fjai
create_music(uploaded_picture_bw, filename, 1, 1)

#iespēja attēlot attēlu, ja vajag
plt.imshow(uploaded_picture);