# -*- coding: utf-8 -*-
"""4.1.1. Melnbalts, pikseļi, atlikumi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZNBkE8vubnl0i3_rnmBi3jUfJYTIC3W
"""

!pip install music21;

#tiek ieimportētas nepieciešamās bibliotēkas
from music21 import instrument, note, stream
from google.colab import files
import matplotlib.pyplot as plt
import numpy as np

#funkcija nošu un MIDI faila veidošana
def create_music (arr, fn, download=True, printMIDI=False):
  output_notes = []
  offset = 0
  
  #tiek veidoti nošu objekti katrai masīva vērtībai 
  #parametrs quarterLenght apzīmē nots garumu ceturtdaļās
  #offset ir nots atskaņošanas laiks attiecībā pret sākumu
  for px in arr:
    new_note = note.Note(px, quarterLength=0.5)
    new_note.offset = offset
    new_note.octave = 4
    new_note.storedInstrument = instrument.Piano()
    output_notes.append(new_note)
    
    #palielina offset katrā iterācijā, lai notis nepārklājas
    offset += 0.5

  #ģenerēto nošu informācija tiek ierakstīta failā    
  midi_stream = stream.Stream(output_notes)
  midi_stream.write('midi', fp='{name}_411.mid'.format(name=fn.split('.')[0]))

  #ģenerēto nošu izprintēšana
  if printMIDI == 1:
    for element in midi_stream:
      print(element.nameWithOctave, element.offset)

  #ģenerētā MIDI faila lejuplāde
  if download == 1:
    files.download('{name}_411.mid'.format(name=fn.split('.')[0]))
  return

#attēla augšupielāde
uploaded = files.upload()

#tiek nolasīts faila nosaukums un pats attēls
filename = list(uploaded.keys())[0]
uploaded_picture=plt.imread(filename)

#attēlam no 3 krāsu dimensijām vispirms tiek izvilkta viena, tad tā tiek saspiesta 1D masīvā
#šim masīvam tiek aprēķināti atlikumi, dalot ar 12
#12 toņus un pustoņus šai bibliotēkā apzīmē skaitļi 0-11
uploaded_picture_bw=np.array(uploaded_picture[:, :, 0]).reshape(uploaded_picture.shape[0]*uploaded_picture.shape[1])%12

#iegūtais masīvs tiek padots mūzikas ģenerēšanas fjai
create_music(uploaded_picture_bw, filename, 1, 1)

#iespēja attēlot attēlu, ja vajag
plt.imshow(uploaded_picture);